### PR TITLE
Update documentation, add disconnect button, change back to single-thread

### PR DESCRIPTION
**Pull request by bparks13**

### CODE REVIEW

**Review by bparks13 — COMMENTED** [review]
@anjaldoshi To confirm, with these changes to the workflows the tag will be automatically pulled from OpenEphysLib.cpp instead of the commit tags, correct? Do we still need to tag the commit to make it easier to browse for specific versions though?

**Comment by anjaldoshi** [comment]
Yes, the updated workflows will pull the version number from `OpenEphysLib.cpp` for deploying.
And yeah, tagging the commits should help us maintain changelogs and checkout specific versions if needed. You can tag after you merge this PR.

**Comment by jonnew** [comment]
Tested, working very well. Good job.

**Comment by Phosphoenix** [comment]
Thanks, this also resolved a bug that made the GUI unresponsive when trying to shut it down with the old socket.

**Pull request merged**
